### ISSUE TITLE
Specify where notebook output goes.

### ISSUE THREAD

**Issue by dirkgruending** [AndreWeiner/phd_notebooks#2]
E.g. in animate_fluxes, the output_path is defined inside a block of the notebook, not at the beginning. Please give me a skype call to explain how this relates to the "volumes" flag handed to the docker command in create_jupyter_container.sh.

**Comment by AndreWeiner** [comment]
The Docker container binds the current directory ($PWD) of the host to the home directory inside the container ($HOME) using the _--volume_ option.  All notebooks are located in a folder called _notebooks_. The script which starts notebooks is also located in that folder. By default, all notebooks write their output to _../output/_. On the host, the results are accessible in the _output_ folder located in the current directory.
