### ISSUE TITLE
Install extensions to jupyter notebook.

### ISSUE THREAD

**Issue by dirkgruending** [AndreWeiner/phd_notebooks#3]
If extensions would be installed, a user could at least see when a block in the notebook has finished. So far I would need to add a "print('Done')" at the end of each block

**Comment by AndreWeiner** [comment]
![timing_notebooks](https://user-images.githubusercontent.com/8482575/76966769-c1d72e80-6926-11ea-82af-c707aab587ae.png)
In Jupyter notebooks, cells that are currently running are highlighted by an asterisk between the square brackets on the left side of each cell, e.g. [*]. Cells performing compute-heavy tasks, e.g. the training of neural networks, use [tqdm](https://github.com/tqdm/tqdm) to indicate the current progress of the training-loop. The progress bar shows the elapsed time, the remaining time, and the current iterations per second.
