### ISSUE TITLE
Bug in basilisk_2D_interface_velocity

### ISSUE THREAD

**Issue by dirkgruending** [AndreWeiner/phd_notebooks#6]
Block [7] fails to find file '../output/models/bhaga_03_l16u_t_norm.pt'
Am I supposed to execute another notebook before? Markdown description does not name any dependencies here.

**Comment by AndreWeiner** [comment]
Fixed by [99a64f07121dfd7eb4227e6c7aa106c47b66236f](https://github.com/AndreWeiner/phd_notebooks/commit/99a64f07121dfd7eb4227e6c7aa106c47b66236f).
