### ISSUE TITLE
Computation advance and time esimate not showing.

### ISSUE THREAD

**Issue by dirkgruending** [AndreWeiner/phd_notebooks#9]
In "eo_re_mo_diagramm" block [4], the progress bar is visible. In the notebooks that are alphabetically before this notebook, the progress bar is not visible.

**Comment by AndreWeiner** [comment]
Please, start the notebook using the provided Docker container as described in the README file, section [Running notebooks](https://github.com/AndreWeiner/phd_notebooks#running-notebooks).
